### ISSUE TITLE
Agent forwarding and adding key from stdin fails

### ISSUE THREAD

**Issue by umglurf** [Foxboron/ssh-tpm-agent#50]
I have an ansible playbook that adds an ssh key to the agent via stdin that fails with the ssh tpm agent. The ssh tpm agent is running with forwarding to another ssh agent, changing `SSH_AUTH_SOCK` to that agent and the ansible playbook works.

The playbook looks like this
```
- name: Add ssh key to ssh agent
  hosts: all
  serial: 1
  gather_facts: false
  tasks:
    - name: Read ansible ssh key
      community.hashi_vault.vault_read:
        url: "{{ vault.url }}"
        path: secret/SOME_PATH
      register: vault_ansible_data
      no_log: true
      delegate_to: localhost
    - name: Add ssh key to ssh agent
      ansible.builtin.command:
        cmd: "ssh-add -"
        stdin: '{{ vault_ansible_data["data"]["data"]["ssh_private_key"] }}'
      no_log: true
      changed_when: false
      delegate_to: localhost
```

Error message from ansible is 
```
Could not add identity \"(stdin)\": agent refused operation"
```
